//loaders
export const DATA_ENABLE_LOADER = 'DATA_ENABLE_LOADER';
export const DATA_DISABLE_LOADER = 'DATA_DISABLE_LOADER';
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
// fetch data
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_RESPONSE = 'FETCH_DATA_RESPONSE';
